// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanningsTool.DAL.Contexts;

#nullable disable

namespace PlanningsTool.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlanningsTool.DAL.Models.Zorgkundige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IsVasteNacht")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblZorgkundigen", "Zorgkundige");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Woerahfa",
                            IsVasteNacht = "0",
                            Voornaam = "Amina"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Tamara",
                            IsVasteNacht = "0",
                            Voornaam = "Barbara"
                        },
                        new
                        {
                            Id = 3,
                            Achternaam = "Dhanitin",
                            IsVasteNacht = "0",
                            Voornaam = "Chaimae"
                        },
                        new
                        {
                            Id = 4,
                            Achternaam = "Dhiyah",
                            IsVasteNacht = "0",
                            Voornaam = "Dalila"
                        },
                        new
                        {
                            Id = 5,
                            Achternaam = "Tsridh",
                            IsVasteNacht = "0",
                            Voornaam = "Fatima"
                        },
                        new
                        {
                            Id = 6,
                            Achternaam = "Mantazoedh",
                            IsVasteNacht = "0",
                            Voornaam = "Ghizlane"
                        },
                        new
                        {
                            Id = 7,
                            Achternaam = "Hanatt",
                            IsVasteNacht = "0",
                            Voornaam = "Halima"
                        },
                        new
                        {
                            Id = 8,
                            Achternaam = "Azough",
                            IsVasteNacht = "0",
                            Voornaam = "Imane"
                        },
                        new
                        {
                            Id = 9,
                            Achternaam = "Adheswe",
                            IsVasteNacht = "0",
                            Voornaam = "Karima"
                        },
                        new
                        {
                            Id = 10,
                            Achternaam = "Adhesha",
                            IsVasteNacht = "1",
                            Voornaam = "Latifa"
                        },
                        new
                        {
                            Id = 11,
                            Achternaam = "Sariedh",
                            IsVasteNacht = "1",
                            Voornaam = "Mariem"
                        },
                        new
                        {
                            Id = 12,
                            Achternaam = "Isira",
                            IsVasteNacht = "1",
                            Voornaam = "Nasira"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
