// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanningsTool.DAL.Contexts;

#nullable disable

namespace PlanningsTool.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231023101115_addRegimeType")]
    partial class addRegimeType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlanningsTool.DAL.Models.RegimeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AantalUren")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("RegimeType", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AantalUren = 38.0m,
                            Regime = "Voltijds"
                        },
                        new
                        {
                            Id = 2,
                            AantalUren = 30.4m,
                            Regime = "Deeltijds 4/5"
                        },
                        new
                        {
                            Id = 3,
                            AantalUren = 28.8m,
                            Regime = "Deeltijds 3/4"
                        },
                        new
                        {
                            Id = 4,
                            AantalUren = 19.0m,
                            Regime = "Halftijds"
                        });
                });

            modelBuilder.Entity("PlanningsTool.DAL.Models.Zorgkundige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IsVasteNacht")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("RegimeId")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RegimeId");

                    b.ToTable("Zorgkundigen", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Woerahfa",
                            IsVasteNacht = "0",
                            RegimeId = 1,
                            Voornaam = "Amina"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Tamara",
                            IsVasteNacht = "0",
                            RegimeId = 1,
                            Voornaam = "Barbara"
                        },
                        new
                        {
                            Id = 3,
                            Achternaam = "Dhanitin",
                            IsVasteNacht = "0",
                            RegimeId = 1,
                            Voornaam = "Chaimae"
                        },
                        new
                        {
                            Id = 4,
                            Achternaam = "Dhiyah",
                            IsVasteNacht = "0",
                            RegimeId = 1,
                            Voornaam = "Dalila"
                        },
                        new
                        {
                            Id = 5,
                            Achternaam = "Tsridh",
                            IsVasteNacht = "0",
                            RegimeId = 2,
                            Voornaam = "Fatima"
                        },
                        new
                        {
                            Id = 6,
                            Achternaam = "Mantazoedh",
                            IsVasteNacht = "0",
                            RegimeId = 2,
                            Voornaam = "Ghizlane"
                        },
                        new
                        {
                            Id = 7,
                            Achternaam = "Hanatt",
                            IsVasteNacht = "0",
                            RegimeId = 2,
                            Voornaam = "Halima"
                        },
                        new
                        {
                            Id = 8,
                            Achternaam = "Azough",
                            IsVasteNacht = "0",
                            RegimeId = 3,
                            Voornaam = "Imane"
                        },
                        new
                        {
                            Id = 9,
                            Achternaam = "Adheswe",
                            IsVasteNacht = "0",
                            RegimeId = 3,
                            Voornaam = "Karima"
                        },
                        new
                        {
                            Id = 10,
                            Achternaam = "Adhesha",
                            IsVasteNacht = "1",
                            RegimeId = 1,
                            Voornaam = "Latifa"
                        },
                        new
                        {
                            Id = 11,
                            Achternaam = "Sariedh",
                            IsVasteNacht = "1",
                            RegimeId = 1,
                            Voornaam = "Mariem"
                        },
                        new
                        {
                            Id = 12,
                            Achternaam = "Isira",
                            IsVasteNacht = "1",
                            RegimeId = 3,
                            Voornaam = "Nasira"
                        });
                });

            modelBuilder.Entity("PlanningsTool.DAL.Models.Zorgkundige", b =>
                {
                    b.HasOne("PlanningsTool.DAL.Models.RegimeType", "Regime")
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regime");
                });
#pragma warning restore 612, 618
        }
    }
}
